import type { Game } from "./types";

/** Display order everywhere (game pickers, dashboard filters). */
export const GAMES: Game[] = ["ultimate", "melee", "roa2"];

export const GAME_LABELS: Record<Game, string> = {
  ultimate: "Ultimate",
  melee: "Melee",
  roa2: "Rivals 2",
};

/** Official game logos (trimmed WebP generated by scripts/make-icons.mjs), with their pixel size. */
export const GAME_LOGOS: Record<Game, { src: string; width: number; height: number }> = {
  ultimate: { src: "/games/ultimate.webp", width: 366, height: 144 },
  melee: { src: "/games/melee.webp", width: 321, height: 144 },
  roa2: { src: "/games/roa2.webp", width: 211, height: 144 },
};

export const DEFAULT_GAME: Game = "ultimate";

export function isGame(value: unknown): value is Game {
  return typeof value === "string" && (GAMES as string[]).includes(value);
}

/** Dashboard URL with that game selected (the default game needs no parameter). */
export function dashboardHref(game: Game) {
  return game === DEFAULT_GAME ? "/" : `/?game=${game}`;
}

/** Example names for the "My character" / "Opponent" fields of the new-matchup form. */
export const CHARACTER_EXAMPLES: Record<Game, [string, string]> = {
  ultimate: ["Marth", "Fox"],
  melee: ["Marth", "Fox"],
  roa2: ["Zetterburn", "Orcane"],
};

export const CHARACTERS: Record<Game, string[]> = {
  ultimate: [
    "Mario", "Donkey Kong", "Link", "Samus", "Dark Samus", "Yoshi", "Kirby", "Fox",
    "Pikachu", "Luigi", "Ness", "Captain Falcon", "Jigglypuff", "Peach", "Daisy",
    "Bowser", "Ice Climbers", "Sheik", "Zelda", "Dr. Mario", "Pichu", "Falco", "Marth",
    "Lucina", "Young Link", "Ganondorf", "Mewtwo", "Roy", "Chrom", "Mr. Game & Watch",
    "Meta Knight", "Pit", "Dark Pit", "Zero Suit Samus", "Wario", "Snake", "Ike",
    "Pokémon Trainer", "Diddy Kong", "Lucas", "Sonic", "King Dedede", "Olimar",
    "Lucario", "R.O.B.", "Toon Link", "Wolf", "Villager", "Mega Man", "Wii Fit Trainer",
    "Rosalina & Luma", "Little Mac", "Greninja", "Mii Brawler", "Mii Swordfighter",
    "Mii Gunner", "Palutena", "Pac-Man", "Robin", "Shulk", "Bowser Jr.", "Duck Hunt",
    "Ryu", "Ken", "Cloud", "Corrin", "Bayonetta", "Inkling", "Ridley", "Simon",
    "Richter", "King K. Rool", "Isabelle", "Incineroar", "Piranha Plant", "Joker",
    "Hero", "Banjo & Kazooie", "Terry", "Byleth", "Min Min", "Steve", "Sephiroth",
    "Pyra / Mythra", "Kazuya", "Sora",
  ],
  melee: [
    "Dr. Mario", "Mario", "Luigi", "Bowser", "Peach", "Yoshi", "Donkey Kong",
    "Captain Falcon", "Ganondorf", "Falco", "Fox", "Ness", "Ice Climbers", "Kirby",
    "Samus", "Zelda", "Sheik", "Link", "Young Link", "Pichu", "Pikachu", "Jigglypuff",
    "Mewtwo", "Mr. Game & Watch", "Marth", "Roy",
  ],
  // Rivals of Aether II: launch roster (2024) + DLC released up to August 2026.
  // Mina the Hollower is announced for 2027: add her once she's out.
  roa2: [
    "Clairen", "Fleet", "Forsburn", "Kragg", "Loxodont", "Maypul", "Orcane", "Ranno",
    "Wrastor", "Zetterburn", "Etalus", "Olympia", "Absa", "Galvan", "La Reina", "Slade",
    "Gouie",
  ],
};

/** Returns the canonical roster spelling if the input matches a known character. */
export function canonicalCharacter(game: Game, input: string): string {
  const needle = input.trim().toLowerCase();
  return CHARACTERS[game].find((c) => c.toLowerCase() === needle) ?? input.trim();
}

/**
 * Abstract platform layouts used to draw a small, original silhouette for each stage.
 * Coordinates live in a 100 × 44 viewBox. `main` is the stage floor [x, width];
 * `platforms` are [x, y, width]. Unknown / custom stages fall back to a flat stage.
 */
export type StageLayout = {
  main: [number, number];
  platforms?: [number, number, number][];
  /** Floor thickness below the walkable surface (default 9). 14 = walls all the way down to the bottom. */
  depth?: number;
  /** How much the floor narrows toward the bottom, as a fraction of its width (default 0.12). */
  taper?: number;
  /** Angle in degrees of the slope next to each ledge (none by default). */
  slope?: number;
  /** Horizontal length of that slope (default 7, as on Yoshi's Story). */
  slopeRun?: number;
  /** Tilt in degrees of the side platforms, outer end lower (parallel to the stage's slopes). */
  platformTilt?: number;
  /** Rounded underside instead of a trapezoid (half-ellipse, `depth` deep). */
  roundBottom?: boolean;
  /** Height of the walkable floor in the viewBox (default 30). Raise it to make room for a deep underside. */
  floorY?: number;
  /** Central support under the floor: [width, height]. */
  pillar?: [number, number];
  /** Solid block under a thin deck, from the floor down to the bottom: [x, width]. The deck overhangs it. */
  body?: [number, number];
};

export const STAGE_LAYOUTS: Record<string, StageLayout> = {
  "Battlefield": { main: [16, 68], platforms: [[24, 21, 18], [58, 21, 18], [41, 11, 18]] },
  "Final Destination": { main: [8, 84] },
  // Same two-platform layout as Pokémon Stadium 2, on a smaller stage.
  "Small Battlefield": { main: [18, 64], platforms: [[26, 21, 16], [58, 21, 16]] },
  // Thin deck held up by a central pillar.
  "Pokémon Stadium 2": {
    main: [8, 84],
    platforms: [[20, 21, 20], [60, 21, 20]],
    depth: 4,
    taper: 0.02,
    pillar: [18, 8],
  },
  // Melee's Stadium: same thin deck and central pillar as Pokémon Stadium 2.
  "Pokémon Stadium": {
    main: [8, 84],
    platforms: [[20, 21, 20], [60, 21, 20]],
    depth: 4,
    taper: 0.02,
    pillar: [18, 8],
  },
  // Centered platform ≈ 45% of the stage width.
  "Hollow Bastion": { main: [8, 84], platforms: [[31, 17, 38]] },
  // Same layout as Hollow Bastion on a smaller, thinner stage; platform ≈ 53% of the stage width.
  "Smashville": { main: [16, 68], platforms: [[32, 17, 36]], depth: 6 },
  // As long as Kalos, thin; side platforms high, centre platform low ( -  _  - ).
  // ~30% of each side platform hangs past the ledge, over the void.
  "Town & City": { main: [10, 80], platforms: [[4.6, 13, 18], [41, 21, 18], [77.4, 13, 18]], depth: 6 },
  // Deep, rectangular stage with perfectly straight walls; each platform is centred right above a ledge.
  "Kalos Pokémon League": { main: [10, 80], platforms: [[2, 19, 16], [82, 19, 16]], depth: 13, taper: 0 },
  // Deeper walls and ~15° slopes next to each ledge.
  "Yoshi's Story": {
    main: [18, 64],
    platforms: [[22, 20, 16], [62, 20, 16], [42, 11, 16]],
    depth: 13,
    taper: 0.06,
    slope: 15,
  },
  // Not in the default Ultimate list since 0007; kept for older notes and custom stages with this name.
  // Flat middle (~65% of the stage), then long ~30° slopes down to the ledges. The side platforms sit over
  // the slopes, tilted parallel to them; the centre platform is just above their highest (inner) ends.
  "Lylat Cruise": {
    main: [14, 72],
    platforms: [[16, 21, 14], [70, 21, 14], [42, 15.5, 16]],
    depth: 10,
    taper: 0.1,
    slope: 30,
    slopeRun: 12.6,
    platformTilt: 30,
  },
  "Dream Land": { main: [10, 80], platforms: [[20, 20, 20], [60, 20, 20], [40, 9, 20]], depth: 12 },
  // Big, almost hemispherical underside: the floor is raised to make room for it (radius 26 × 22 deep).
  "Fountain of Dreams": {
    main: [24, 52],
    platforms: [[28, 12.5, 13], [59, 12.5, 13], [43.5, 3.5, 13]],
    floorY: 22,
    depth: 22,
    roundBottom: true,
  },

  // ── Rivals of Aether II (layouts from dragdown.wiki/wiki/RoA2/Stages) ──
  // Stage widths are scaled from the in-game lengths (1250 → 50, 2020 → 84) so relative sizes stay readable.
  // Most stages have straight walls from the ledge down to the bottom blast zone (depth 14, no taper);
  // the exceptions are Air Armada and Hyperborean Harbor. No arrows: moving parts are shown at rest.
  // Smallest stage; one platform in the middle (it swings left and right in game).
  "Aetherian Forest": { main: [24.5, 51], platforms: [[43.5, 20, 13]], depth: 14, taper: 0 },
  // Symmetrical side platforms, the lowest of all starters.
  "Godai Delta": { main: [17, 66], platforms: [[25.5, 22, 16.5], [58, 22, 16.5]], depth: 14, taper: 0 },
  // Tri-plat with the tallest platforms of the starters.
  "Hodojo": { main: [20.5, 59], platforms: [[24.5, 19, 11], [64.5, 19, 11], [44.5, 9.5, 11]], depth: 14, taper: 0 },
  // High platform sliding left ↔ right; a small low platform drifts across and disappears.
  "Julesvale": { main: [21.5, 57], platforms: [[44.5, 11, 11], [28, 22, 8]], depth: 14, taper: 0 },
  // Two platforms that join in the middle, then split over the abyss; slightly slanted walls that stop
  // above the bottom blast zone. Longer than Metal Refinery (1900 vs 1680). In the default list since 0006.
  "Air Armada": { main: [10.5, 79], platforms: [[29, 18, 20.5], [50.5, 18, 20.5]], depth: 11, taper: 0.07 },
  // Same moving platforms, full walls down to the blast zone. Replaced by Air Armada in the default list (0006);
  // kept so older notes or custom stages with this name still get their silhouette.
  "Metal Refinery": { main: [15.5, 69], platforms: [[31, 18, 18.5], [50.5, 18, 18.5]], depth: 14, taper: 0 },
  // As long as Fire Capital. Side platforms flush with the stage edges; two smaller raised ones near the middle.
  "Merchant Port": {
    main: [8, 84],
    platforms: [[8, 21, 12], [80, 21, 12], [34.5, 12, 9], [56.5, 12, 9]],
    depth: 14,
    taper: 0,
  },
  // Longest stage; opposite of Merchant Port: raised platforms near the edges, low ones near the centre.
  "Fire Capital": {
    main: [8, 84],
    platforms: [[12, 11, 10.5], [77.5, 11, 10.5], [33, 23, 10.5], [56.5, 23, 10.5]],
    depth: 14,
    taper: 0,
  },
  // From the owner's sketch: a thin deck whose ledges overhang a narrower body going down to the bottom;
  // three platforms at about the same height, the outer two reaching past the ledges.
  "Hyperborean Harbor": {
    main: [10.9, 76.3],
    platforms: [[2.3, 14.5, 18.6], [38, 15.2, 20], [74.5, 14.6, 19.1]],
    depth: 2.5,
    taper: 0,
    body: [29.5, 37.7],
  },
  // Two columns of stacked platforms (the top ones are the tallest in the game), open space in between.
  "Rock Wall": {
    main: [11.5, 77],
    platforms: [[19, 20, 11], [70, 20, 11], [19, 8, 11], [70, 8, 11]],
    depth: 14,
    taper: 0,
  },
  // Small stage; two wide platforms that take turns rising and lowering.
  "Tempest Peak": { main: [25, 50], platforms: [[27, 15, 17], [56, 22, 17]], depth: 14, taper: 0 },
};

export const DEFAULT_LAYOUT: StageLayout = { main: [12, 76] };

/** Top of the stage floor in the 100 × 44 viewBox. */
export const FLOOR_Y = 30;
/** Bottom edge of the viewBox (walls with `depth: 14` reach it). */
const VIEW_BOTTOM = 44;
/** Default horizontal length of the sloped section next to each ledge (when `slope` is set). */
const SLOPE_RUN = 7;
/** Platform thickness. */
const PLATFORM_H = 2.2;

const r = (n: number) => Math.round(n * 100) / 100;
const rad = (deg: number) => (deg * Math.PI) / 180;

/** SVG path data for the stage floor (and its pillar / body, if any). */
export function stageFloorPaths(layout: StageLayout): string[] {
  const [x, w] = layout.main;
  const top = layout.floorY ?? FLOOR_Y;
  const depth = layout.depth ?? 9;
  const bottom = Math.min(top + depth, VIEW_BOTTOM);
  const paths: string[] = [];

  if (layout.roundBottom) {
    // Flat top, half-ellipse underneath.
    paths.push(`M${r(x)} ${top} L${r(x + w)} ${top} A${r(w / 2)} ${r(bottom - top)} 0 0 1 ${r(x)} ${top} Z`);
  } else {
    const inset = w * (layout.taper ?? 0.12);
    const run = layout.slope ? (layout.slopeRun ?? SLOPE_RUN) : 0;
    const drop = layout.slope ? run * Math.tan(rad(layout.slope)) : 0;
    paths.push(
      [
        `M${r(x)} ${r(top + drop)}`,
        `L${r(x + run)} ${top}`,
        `L${r(x + w - run)} ${top}`,
        `L${r(x + w)} ${r(top + drop)}`,
        `L${r(x + w - inset)} ${bottom}`,
        `L${r(x + inset)} ${bottom}`,
        "Z",
      ].join(" "),
    );
  }

  if (layout.body) {
    const [bx, bw] = layout.body;
    paths.push(`M${r(bx)} ${bottom} h${r(bw)} V${VIEW_BOTTOM} h${r(-bw)} Z`);
  }

  if (layout.pillar) {
    const [pw, ph] = layout.pillar;
    const cx = x + w / 2;
    paths.push(`M${r(cx - pw / 2)} ${bottom} h${pw} l-1.5 ${ph} h-${pw - 3} Z`);
  }

  return paths;
}

/**
 * SVG path data for one platform [x, y, width]: a bar with rounded ends. With `platformTilt`, side
 * platforms (left or right of centre) are rotated around their centre, outer end lower; the centre one stays flat.
 */
export function platformPath(layout: StageLayout, [px, py, pw]: [number, number, number]): string {
  const cx = px + pw / 2;
  const cy = py + PLATFORM_H / 2;
  const side = !layout.platformTilt || Math.abs(cx - 50) < 8 ? 0 : cx < 50 ? -1 : 1;
  // Screen y points down: a positive angle lowers the right end, a negative one the left end.
  const a = rad((layout.platformTilt ?? 0) * side);
  const [cos, sin] = [Math.cos(a), Math.sin(a)];
  const at = (dx: number, dy: number) => `${r(cx + dx * cos - dy * sin)} ${r(cy + dx * sin + dy * cos)}`;

  const half = pw / 2;
  const c = PLATFORM_H / 2; // end radius
  return `M${at(-half + c, -c)} L${at(half - c, -c)} A${c} ${c} 0 0 1 ${at(half - c, c)} L${at(-half + c, c)} A${c} ${c} 0 0 1 ${at(-half + c, -c)} Z`;
}
