import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * "SMASH MEMO" + pen wordmark in ink (generated by scripts/make-icons.mjs):
 * blue-black on paper, chalk on the dark slate theme.
 */
export function BrandLogo({ className }: { className?: string }) {
  return (
    <>
      <Image
        src="/brand/logo-long-light.png"
        alt="Smash Memo"
        width={484}
        height={160}
        priority
        className={cn("h-9 w-auto dark:hidden", className)}
      />
      <Image
        src="/brand/logo-long-dark.png"
        alt="Smash Memo"
        width={484}
        height={160}
        priority
        className={cn("hidden h-9 w-auto dark:block", className)}
      />
    </>
  );
}
