import Image from "next/image";
import { cn } from "@/lib/cn";

/** "SMASH MEMO" + pen wordmark (transparent PNG generated by scripts/make-icons.mjs). */
export function BrandLogo({ className }: { className?: string }) {
  return (
    <Image
      src="/brand/logo-long.png"
      alt="Smash Mémo"
      width={484}
      height={160}
      priority
      className={cn("h-9 w-auto", className)}
    />
  );
}
